import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NoFlashThemeProvider } from "@/components/no-flash-theme-provider";
import { AuthProvider } from "@/contexts/auth-context";
import { ReduxProvider } from "@/providers/redux-provider";
import { NavigationProvider } from "@/contexts/navigation-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <NoFlashThemeProvider storageKey="dashboard-theme">
          <ReduxProvider>
            <AuthProvider>
              <NavigationProvider>
                {children}
              </NavigationProvider>
            </AuthProvider>
          </ReduxProvider>
        </NoFlashThemeProvider>
      </body>
    </html>
  );
}
